version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - /pkg
      - /tools
    schedule:
      interval: daily
    labels:
      - dependencies
    groups:
      gomod:
        update-types:
          - "patch"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        update-types:
          - "minor"
          - "patch"
