// Code generated by tools/generator. DO NOT EDIT.

/*
Copyright 2023 The CDEvents Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

SPDX-License-Identifier: Apache-2.0
*/

package api

import "time"

var (
	// ChangeCreated event type v0.3.0
	ChangeCreatedEventTypeV0_3_0 CDEventType = CDEventType{
		Subject:   "change",
		Predicate: "created",
		Version:   "0.3.0",
	}
)

type ChangeCreatedSubjectContentV0_3_0 struct {
	Description string `json:"description,omitempty"`

	Repository *Reference `json:"repository,omitempty"`
}

type ChangeCreatedSubjectV0_3_0 struct {
	SubjectBase
	Content ChangeCreatedSubjectContentV0_3_0 `json:"content"`
}

func (sc ChangeCreatedSubjectV0_3_0) GetSubjectType() SubjectType {
	return "change"
}

type ChangeCreatedEventV0_3_0 struct {
	Context Context                    `json:"context"`
	Subject ChangeCreatedSubjectV0_3_0 `json:"subject"`
	CDEventCustomData
}

// CDEventsReader implementation

func (e ChangeCreatedEventV0_3_0) GetType() CDEventType {
	return ChangeCreatedEventTypeV0_3_0
}

func (e ChangeCreatedEventV0_3_0) GetVersion() string {
	return CDEventsSpecVersion
}

func (e ChangeCreatedEventV0_3_0) GetId() string {
	return e.Context.Id
}

func (e ChangeCreatedEventV0_3_0) GetSource() string {
	return e.Context.Source
}

func (e ChangeCreatedEventV0_3_0) GetTimestamp() time.Time {
	return e.Context.Timestamp
}

func (e ChangeCreatedEventV0_3_0) GetSubjectId() string {
	return e.Subject.Id
}

func (e ChangeCreatedEventV0_3_0) GetSubjectSource() string {
	return e.Subject.Source
}

func (e ChangeCreatedEventV0_3_0) GetSubject() Subject {
	return e.Subject
}

func (e ChangeCreatedEventV0_3_0) GetCustomData() (interface{}, error) {
	return GetCustomData(e.CustomDataContentType, e.CustomData)
}

func (e ChangeCreatedEventV0_3_0) GetCustomDataAs(receiver interface{}) error {
	return GetCustomDataAs(e, receiver)
}

func (e ChangeCreatedEventV0_3_0) GetCustomDataRaw() ([]byte, error) {
	return GetCustomDataRaw(e.CustomDataContentType, e.CustomData)
}

func (e ChangeCreatedEventV0_3_0) GetCustomDataContentType() string {
	return e.CustomDataContentType
}

// CDEventsWriter implementation

func (e *ChangeCreatedEventV0_3_0) SetId(id string) {
	e.Context.Id = id
}

func (e *ChangeCreatedEventV0_3_0) SetSource(source string) {
	e.Context.Source = source
	// Default the subject source to the event source
	if e.Subject.Source == "" {
		e.Subject.Source = source
	}
}

func (e *ChangeCreatedEventV0_3_0) SetTimestamp(timestamp time.Time) {
	e.Context.Timestamp = timestamp
}

func (e *ChangeCreatedEventV0_3_0) SetSubjectId(subjectId string) {
	e.Subject.Id = subjectId
}

func (e *ChangeCreatedEventV0_3_0) SetSubjectSource(subjectSource string) {
	e.Subject.Source = subjectSource
}

func (e *ChangeCreatedEventV0_3_0) SetCustomData(contentType string, data interface{}) error {
	err := CheckCustomData(contentType, data)
	if err != nil {
		return err
	}
	e.CustomData = data
	e.CustomDataContentType = contentType
	return nil
}

func (e ChangeCreatedEventV0_3_0) GetSchema() (string, string) {
	eType := e.GetType()
	id, schema, _ := GetSchemaBySpecSubjectPredicate(CDEventsSpecVersion, eType.Subject, eType.Predicate)
	return id, schema
}

// Set subject custom fields

func (e *ChangeCreatedEventV0_3_0) SetSubjectDescription(description string) {
	e.Subject.Content.Description = description
}

func (e *ChangeCreatedEventV0_3_0) SetSubjectRepository(repository *Reference) {
	e.Subject.Content.Repository = repository
}

// New creates a new ChangeCreatedEventV0_3_0
func NewChangeCreatedEventV0_3_0(specVersion string) (*ChangeCreatedEventV0_3_0, error) {
	e := &ChangeCreatedEventV0_3_0{
		Context: Context{
			Type:    ChangeCreatedEventTypeV0_3_0,
			Version: specVersion,
		},
		Subject: ChangeCreatedSubjectV0_3_0{
			SubjectBase: SubjectBase{
				Type: "change",
			},
		},
	}
	_, err := initCDEvent(e)
	if err != nil {
		return nil, err
	}
	return e, nil
}
