// Code generated by tools/generator. DO NOT EDIT.

/*
Copyright 2023 The CDEvents Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

SPDX-License-Identifier: Apache-2.0
*/

package api

import (
	"fmt"
	"time"

	jsonschema "github.com/santhosh-tekuri/jsonschema/v6"
)

var (
	// CustomType event type v0.5.0
	CustomTypeEventTypeV0_5_0 CDEventType = CDEventType{}
)

type CustomTypeSubjectV0_5_0 struct {
	SubjectBaseV05
	Content interface{} `json:"content"`
}

func (sc CustomTypeSubjectV0_5_0) GetSubjectType() SubjectType {
	return ""
}

type CustomTypeEventV0_5_0 struct {
	Context ContextV05              `json:"context"`
	Subject CustomTypeSubjectV0_5_0 `json:"subject"`
	CDEventCustomData
}

// CDEventsReader implementation

func (e CustomTypeEventV0_5_0) GetType() CDEventType {
	return CustomTypeEventTypeV0_5_0
}

func (e CustomTypeEventV0_5_0) GetVersion() string {
	return e.Context.GetVersion()
}

func (e CustomTypeEventV0_5_0) GetId() string {
	return e.Context.Id
}

func (e CustomTypeEventV0_5_0) GetSource() string {
	return e.Context.Source
}

func (e CustomTypeEventV0_5_0) GetTimestamp() time.Time {
	return e.Context.Timestamp
}

func (e CustomTypeEventV0_5_0) GetSubjectId() string {
	return e.Subject.Id
}

func (e CustomTypeEventV0_5_0) GetSubjectSource() string {
	return e.Subject.Source
}

func (e CustomTypeEventV0_5_0) GetSubject() Subject {
	return e.Subject
}

func (e CustomTypeEventV0_5_0) GetCustomData() (interface{}, error) {
	return GetCustomData(e.CustomDataContentType, e.CustomData)
}

func (e CustomTypeEventV0_5_0) GetCustomDataAs(receiver interface{}) error {
	return GetCustomDataAs(e, receiver)
}

func (e CustomTypeEventV0_5_0) GetCustomDataRaw() ([]byte, error) {
	return GetCustomDataRaw(e.CustomDataContentType, e.CustomData)
}

func (e CustomTypeEventV0_5_0) GetCustomDataContentType() string {
	return e.CustomDataContentType
}

// CDEventsReaderV04 implementation

func (e CustomTypeEventV0_5_0) GetChainId() string {
	return e.Context.ChainId
}

func (e CustomTypeEventV0_5_0) GetLinks() EmbeddedLinksArray {
	return e.Context.Links
}

func (e CustomTypeEventV0_5_0) GetSchemaUri() string {
	return e.Context.SchemaUri
}

// GetCustomSchema looks up the SchemaUri, if any is defined. If none is defined, it returns nil.
// If it's defined and cannot be found, it returns an error.
func (e CustomTypeEventV0_5_0) GetCustomSchema() (*jsonschema.Schema, error) {
	schemaUri := e.GetSchemaUri()
	if schemaUri == "" {
		return nil, nil
	}
	schema, found := CompiledCustomSchemas[schemaUri]
	if !found {
		return nil, fmt.Errorf("schema with id %s could not be found in the local registry", schemaUri)
	}
	return schema, nil
}

// CDEventsWriter implementation

func (e *CustomTypeEventV0_5_0) SetId(id string) {
	e.Context.Id = id
}

func (e *CustomTypeEventV0_5_0) SetSource(source string) {
	e.Context.Source = source
	// Default the subject source to the event source
	if e.Subject.Source == "" {
		e.Subject.Source = source
	}
}

func (e *CustomTypeEventV0_5_0) SetTimestamp(timestamp time.Time) {
	e.Context.Timestamp = timestamp
}

func (e *CustomTypeEventV0_5_0) SetSubjectId(subjectId string) {
	e.Subject.Id = subjectId
}

func (e *CustomTypeEventV0_5_0) SetSubjectSource(subjectSource string) {
	e.Subject.Source = subjectSource
}

func (e *CustomTypeEventV0_5_0) SetCustomData(contentType string, data interface{}) error {
	err := CheckCustomData(contentType, data)
	if err != nil {
		return err
	}
	e.CustomData = data
	e.CustomDataContentType = contentType
	return nil
}

func (e CustomTypeEventV0_5_0) GetSchema() (string, *jsonschema.Schema, error) {
	eType := e.GetType()
	return CompiledSchemas.GetBySpecSubjectPredicate("0.5.0", eType.Subject, eType.Predicate, eType.Custom)
}

// CDEventsWriterV04 implementation

func (e *CustomTypeEventV0_5_0) SetChainId(chainId string) {
	e.Context.ChainId = chainId
}

func (e *CustomTypeEventV0_5_0) SetLinks(links EmbeddedLinksArray) {
	e.Context.Links = links
}

func (e *CustomTypeEventV0_5_0) SetSchemaUri(schema string) {
	e.Context.SchemaUri = schema
}

func (e CustomTypeEventV0_5_0) GetSubjectContent() interface{} {
	return e.Subject.Content
}

// CustomCDEventWriter implementation

func (e *CustomTypeEventV0_5_0) SetEventType(eventType CDEventType) {
	e.Context.Type = eventType
}

// CustomCDEvent types can have different subject fields
func (e *CustomTypeEventV0_5_0) SetSubjectContent(subjectContent interface{}) {
	e.Subject.Content = subjectContent
}

// New creates a new CustomTypeEventV0_5_0
func NewCustomTypeEventV0_5_0(specVersion string) (*CustomTypeEventV0_5_0, error) {
	e := &CustomTypeEventV0_5_0{
		Context: ContextV05{
			SharedContext: SharedContext{
				Type: CustomTypeEventTypeV0_5_0,
			},
			SpecVersion:   specVersion,
			ContextLinks:  ContextLinks{},
			ContextCustom: ContextCustom{},
		},
		Subject: CustomTypeSubjectV0_5_0{
			SubjectBaseV05: SubjectBaseV05{},
		},
	}
	_, err := initCDEvent(e)
	if err != nil {
		return nil, err
	}
	return e, nil
}
