// Code generated by tools/generator. DO NOT EDIT.

/*
Copyright 2023 The CDEvents Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

SPDX-License-Identifier: Apache-2.0
*/

package api

import (
	"time"

	jsonschema "github.com/santhosh-tekuri/jsonschema/v6"
)

var (
	// CustomType event type v0.4.1
	CustomTypeEventTypeV0_4_1 CDEventType = CDEventType{}
)

type CustomTypeSubjectV0_4_1 struct {
	SubjectBase
	Content interface{} `json:"content"`
}

func (sc CustomTypeSubjectV0_4_1) GetSubjectType() SubjectType {
	return sc.Type
}

type CustomTypeEventV0_4_1 struct {
	Context ContextV04              `json:"context"`
	Subject CustomTypeSubjectV0_4_1 `json:"subject"`
	CDEventCustomData
}

// CDEventsReader implementation

func (e CustomTypeEventV0_4_1) GetType() CDEventType {
	return CustomTypeEventTypeV0_4_1
}

func (e CustomTypeEventV0_4_1) GetVersion() string {
	return e.Context.GetVersion()
}

func (e CustomTypeEventV0_4_1) GetId() string {
	return e.Context.Id
}

func (e CustomTypeEventV0_4_1) GetSource() string {
	return e.Context.Source
}

func (e CustomTypeEventV0_4_1) GetTimestamp() time.Time {
	return e.Context.Timestamp
}

func (e CustomTypeEventV0_4_1) GetSubjectId() string {
	return e.Subject.Id
}

func (e CustomTypeEventV0_4_1) GetSubjectSource() string {
	return e.Subject.Source
}

func (e CustomTypeEventV0_4_1) GetSubject() Subject {
	return e.Subject
}

func (e CustomTypeEventV0_4_1) GetCustomData() (interface{}, error) {
	return GetCustomData(e.CustomDataContentType, e.CustomData)
}

func (e CustomTypeEventV0_4_1) GetCustomDataAs(receiver interface{}) error {
	return GetCustomDataAs(e, receiver)
}

func (e CustomTypeEventV0_4_1) GetCustomDataRaw() ([]byte, error) {
	return GetCustomDataRaw(e.CustomDataContentType, e.CustomData)
}

func (e CustomTypeEventV0_4_1) GetCustomDataContentType() string {
	return e.CustomDataContentType
}

// CDEventsReaderV04 implementation

func (e CustomTypeEventV0_4_1) GetChainId() string {
	return e.Context.ChainId
}

func (e CustomTypeEventV0_4_1) GetLinks() EmbeddedLinksArray {
	return e.Context.Links
}

func (e CustomTypeEventV0_4_1) GetSchemaUri() string {
	return e.Context.SchemaUri
}

// CDEventsWriter implementation

func (e *CustomTypeEventV0_4_1) SetId(id string) {
	e.Context.Id = id
}

func (e *CustomTypeEventV0_4_1) SetSource(source string) {
	e.Context.Source = source
	// Default the subject source to the event source
	if e.Subject.Source == "" {
		e.Subject.Source = source
	}
}

func (e *CustomTypeEventV0_4_1) SetTimestamp(timestamp time.Time) {
	e.Context.Timestamp = timestamp
}

func (e *CustomTypeEventV0_4_1) SetSubjectId(subjectId string) {
	e.Subject.Id = subjectId
}

func (e *CustomTypeEventV0_4_1) SetSubjectSource(subjectSource string) {
	e.Subject.Source = subjectSource
}

func (e *CustomTypeEventV0_4_1) SetCustomData(contentType string, data interface{}) error {
	err := CheckCustomData(contentType, data)
	if err != nil {
		return err
	}
	e.CustomData = data
	e.CustomDataContentType = contentType
	return nil
}

func (e CustomTypeEventV0_4_1) GetSchema() (string, *jsonschema.Schema, error) {
	eType := e.GetType()
	return CompiledSchemas.GetBySpecSubjectPredicate("0.4.1", eType.Subject, eType.Predicate, eType.Custom)
}

// CDEventsWriterV04 implementation

func (e *CustomTypeEventV0_4_1) SetChainId(chainId string) {
	e.Context.ChainId = chainId
}

func (e *CustomTypeEventV0_4_1) SetLinks(links EmbeddedLinksArray) {
	e.Context.Links = links
}

func (e *CustomTypeEventV0_4_1) SetSchemaUri(schema string) {
	e.Context.SchemaUri = schema
}

func (e CustomTypeEventV0_4_1) GetSubjectContent() interface{} {
	return e.Subject.Content
}

// CustomCDEventWriter implementation

func (e *CustomTypeEventV0_4_1) SetEventType(eventType CDEventType) {
	e.Context.Type = eventType
	e.Subject.Type = SubjectType(eventType.FQSubject())
}

// CustomCDEvent types can have different subject fields
func (e *CustomTypeEventV0_4_1) SetSubjectContent(subjectContent interface{}) {
	e.Subject.Content = subjectContent
}

// New creates a new CustomTypeEventV0_4_1
func NewCustomTypeEventV0_4_1(specVersion string) (*CustomTypeEventV0_4_1, error) {
	e := &CustomTypeEventV0_4_1{
		Context: ContextV04{
			Context{
				Type:    CustomTypeEventTypeV0_4_1,
				Version: specVersion,
			},
			ContextLinks{},
			ContextCustom{},
		},
		Subject: CustomTypeSubjectV0_4_1{
			SubjectBase: SubjectBase{
				Type: "",
			},
		},
	}
	_, err := initCDEvent(e)
	if err != nil {
		return nil, err
	}
	return e, nil
}
