// Code generated by tools/generator. DO NOT EDIT.

/*
Copyright 2023 The CDEvents Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

SPDX-License-Identifier: Apache-2.0
*/

package api_test

import (
	"github.com/cdevents/sdk-go/pkg/api"
	specv03 "github.com/cdevents/sdk-go/pkg/api/v03"
)

func init() {
	// Create events equal to examples in the spec
	examplesProduced = make(map[string]api.CDEvent)
	// ArtifactPackaged Event producer
	newArtifactPackaged, _ := specv03.NewArtifactPackagedEvent()
	setContext(newArtifactPackaged, testSubjectId)
	exampleArtifactPackagedEvent(newArtifactPackaged)
	examplesProduced[newArtifactPackaged.GetType().Short()] = newArtifactPackaged

	// ArtifactPublished Event producer
	newArtifactPublished, _ := specv03.NewArtifactPublishedEvent()
	setContext(newArtifactPublished, testSubjectId)
	exampleArtifactPublishedEvent(newArtifactPublished)
	examplesProduced[newArtifactPublished.GetType().Short()] = newArtifactPublished

	// ArtifactSigned Event producer
	newArtifactSigned, _ := specv03.NewArtifactSignedEvent()
	setContext(newArtifactSigned, testSubjectId)
	exampleArtifactSignedEvent(newArtifactSigned)
	examplesProduced[newArtifactSigned.GetType().Short()] = newArtifactSigned

	// BranchCreated Event producer
	newBranchCreated, _ := specv03.NewBranchCreatedEvent()
	setContext(newBranchCreated, testSubjectId)
	exampleBranchCreatedEvent(newBranchCreated)
	examplesProduced[newBranchCreated.GetType().Short()] = newBranchCreated

	// BranchDeleted Event producer
	newBranchDeleted, _ := specv03.NewBranchDeletedEvent()
	setContext(newBranchDeleted, testSubjectId)
	exampleBranchDeletedEvent(newBranchDeleted)
	examplesProduced[newBranchDeleted.GetType().Short()] = newBranchDeleted

	// BuildFinished Event producer
	newBuildFinished, _ := specv03.NewBuildFinishedEvent()
	setContext(newBuildFinished, testSubjectId)
	exampleBuildFinishedEvent(newBuildFinished)
	examplesProduced[newBuildFinished.GetType().Short()] = newBuildFinished

	// BuildQueued Event producer
	newBuildQueued, _ := specv03.NewBuildQueuedEvent()
	setContext(newBuildQueued, testSubjectId)
	exampleBuildQueuedEvent(newBuildQueued)
	examplesProduced[newBuildQueued.GetType().Short()] = newBuildQueued

	// BuildStarted Event producer
	newBuildStarted, _ := specv03.NewBuildStartedEvent()
	setContext(newBuildStarted, testSubjectId)
	exampleBuildStartedEvent(newBuildStarted)
	examplesProduced[newBuildStarted.GetType().Short()] = newBuildStarted

	// ChangeAbandoned Event producer
	newChangeAbandoned, _ := specv03.NewChangeAbandonedEvent()
	setContext(newChangeAbandoned, testSubjectId)
	exampleChangeAbandonedEvent(newChangeAbandoned)
	examplesProduced[newChangeAbandoned.GetType().Short()] = newChangeAbandoned

	// ChangeCreated Event producer
	newChangeCreated, _ := specv03.NewChangeCreatedEvent()
	setContext(newChangeCreated, testSubjectId)
	exampleChangeCreatedEvent(newChangeCreated)
	examplesProduced[newChangeCreated.GetType().Short()] = newChangeCreated

	// ChangeMerged Event producer
	newChangeMerged, _ := specv03.NewChangeMergedEvent()
	setContext(newChangeMerged, testSubjectId)
	exampleChangeMergedEvent(newChangeMerged)
	examplesProduced[newChangeMerged.GetType().Short()] = newChangeMerged

	// ChangeReviewed Event producer
	newChangeReviewed, _ := specv03.NewChangeReviewedEvent()
	setContext(newChangeReviewed, testSubjectId)
	exampleChangeReviewedEvent(newChangeReviewed)
	examplesProduced[newChangeReviewed.GetType().Short()] = newChangeReviewed

	// ChangeUpdated Event producer
	newChangeUpdated, _ := specv03.NewChangeUpdatedEvent()
	setContext(newChangeUpdated, testSubjectId)
	exampleChangeUpdatedEvent(newChangeUpdated)
	examplesProduced[newChangeUpdated.GetType().Short()] = newChangeUpdated

	// EnvironmentCreated Event producer
	newEnvironmentCreated, _ := specv03.NewEnvironmentCreatedEvent()
	setContext(newEnvironmentCreated, testSubjectId)
	exampleEnvironmentCreatedEvent(newEnvironmentCreated)
	examplesProduced[newEnvironmentCreated.GetType().Short()] = newEnvironmentCreated

	// EnvironmentDeleted Event producer
	newEnvironmentDeleted, _ := specv03.NewEnvironmentDeletedEvent()
	setContext(newEnvironmentDeleted, testSubjectId)
	exampleEnvironmentDeletedEvent(newEnvironmentDeleted)
	examplesProduced[newEnvironmentDeleted.GetType().Short()] = newEnvironmentDeleted

	// EnvironmentModified Event producer
	newEnvironmentModified, _ := specv03.NewEnvironmentModifiedEvent()
	setContext(newEnvironmentModified, testSubjectId)
	exampleEnvironmentModifiedEvent(newEnvironmentModified)
	examplesProduced[newEnvironmentModified.GetType().Short()] = newEnvironmentModified

	// IncidentDetected Event producer
	newIncidentDetected, _ := specv03.NewIncidentDetectedEvent()
	setContext(newIncidentDetected, testSubjectId)
	exampleIncidentDetectedEvent(newIncidentDetected)
	examplesProduced[newIncidentDetected.GetType().Short()] = newIncidentDetected

	// IncidentReported Event producer
	newIncidentReported, _ := specv03.NewIncidentReportedEvent()
	setContext(newIncidentReported, testSubjectId)
	exampleIncidentReportedEvent(newIncidentReported)
	examplesProduced[newIncidentReported.GetType().Short()] = newIncidentReported

	// IncidentResolved Event producer
	newIncidentResolved, _ := specv03.NewIncidentResolvedEvent()
	setContext(newIncidentResolved, testSubjectId)
	exampleIncidentResolvedEvent(newIncidentResolved)
	examplesProduced[newIncidentResolved.GetType().Short()] = newIncidentResolved

	// PipelineRunFinished Event producer
	newPipelineRunFinished, _ := specv03.NewPipelineRunFinishedEvent()
	setContext(newPipelineRunFinished, testSubjectId)
	examplePipelineRunFinishedEvent(newPipelineRunFinished)
	examplesProduced[newPipelineRunFinished.GetType().Short()] = newPipelineRunFinished

	// PipelineRunQueued Event producer
	newPipelineRunQueued, _ := specv03.NewPipelineRunQueuedEvent()
	setContext(newPipelineRunQueued, testSubjectId)
	examplePipelineRunQueuedEvent(newPipelineRunQueued)
	examplesProduced[newPipelineRunQueued.GetType().Short()] = newPipelineRunQueued

	// PipelineRunStarted Event producer
	newPipelineRunStarted, _ := specv03.NewPipelineRunStartedEvent()
	setContext(newPipelineRunStarted, testSubjectId)
	examplePipelineRunStartedEvent(newPipelineRunStarted)
	examplesProduced[newPipelineRunStarted.GetType().Short()] = newPipelineRunStarted

	// RepositoryCreated Event producer
	newRepositoryCreated, _ := specv03.NewRepositoryCreatedEvent()
	setContext(newRepositoryCreated, testSubjectId)
	exampleRepositoryCreatedEvent(newRepositoryCreated)
	examplesProduced[newRepositoryCreated.GetType().Short()] = newRepositoryCreated

	// RepositoryDeleted Event producer
	newRepositoryDeleted, _ := specv03.NewRepositoryDeletedEvent()
	setContext(newRepositoryDeleted, testSubjectId)
	exampleRepositoryDeletedEvent(newRepositoryDeleted)
	examplesProduced[newRepositoryDeleted.GetType().Short()] = newRepositoryDeleted

	// RepositoryModified Event producer
	newRepositoryModified, _ := specv03.NewRepositoryModifiedEvent()
	setContext(newRepositoryModified, testSubjectId)
	exampleRepositoryModifiedEvent(newRepositoryModified)
	examplesProduced[newRepositoryModified.GetType().Short()] = newRepositoryModified

	// ServiceDeployed Event producer
	newServiceDeployed, _ := specv03.NewServiceDeployedEvent()
	setContext(newServiceDeployed, testSubjectId)
	exampleServiceDeployedEvent(newServiceDeployed)
	examplesProduced[newServiceDeployed.GetType().Short()] = newServiceDeployed

	// ServicePublished Event producer
	newServicePublished, _ := specv03.NewServicePublishedEvent()
	setContext(newServicePublished, testSubjectId)
	exampleServicePublishedEvent(newServicePublished)
	examplesProduced[newServicePublished.GetType().Short()] = newServicePublished

	// ServiceRemoved Event producer
	newServiceRemoved, _ := specv03.NewServiceRemovedEvent()
	setContext(newServiceRemoved, testSubjectId)
	exampleServiceRemovedEvent(newServiceRemoved)
	examplesProduced[newServiceRemoved.GetType().Short()] = newServiceRemoved

	// ServiceRolledback Event producer
	newServiceRolledback, _ := specv03.NewServiceRolledbackEvent()
	setContext(newServiceRolledback, testSubjectId)
	exampleServiceRolledbackEvent(newServiceRolledback)
	examplesProduced[newServiceRolledback.GetType().Short()] = newServiceRolledback

	// ServiceUpgraded Event producer
	newServiceUpgraded, _ := specv03.NewServiceUpgradedEvent()
	setContext(newServiceUpgraded, testSubjectId)
	exampleServiceUpgradedEvent(newServiceUpgraded)
	examplesProduced[newServiceUpgraded.GetType().Short()] = newServiceUpgraded

	// TaskRunFinished Event producer
	newTaskRunFinished, _ := specv03.NewTaskRunFinishedEvent()
	setContext(newTaskRunFinished, testSubjectId)
	exampleTaskRunFinishedEvent(newTaskRunFinished)
	examplesProduced[newTaskRunFinished.GetType().Short()] = newTaskRunFinished

	// TaskRunStarted Event producer
	newTaskRunStarted, _ := specv03.NewTaskRunStartedEvent()
	setContext(newTaskRunStarted, testSubjectId)
	exampleTaskRunStartedEvent(newTaskRunStarted)
	examplesProduced[newTaskRunStarted.GetType().Short()] = newTaskRunStarted

	// TestCaseRunFinished Event producer
	newTestCaseRunFinished, _ := specv03.NewTestCaseRunFinishedEvent()
	setContext(newTestCaseRunFinished, testSubjectId)
	exampleTestCaseRunFinishedEvent(newTestCaseRunFinished)
	examplesProduced[newTestCaseRunFinished.GetType().Short()] = newTestCaseRunFinished

	// TestCaseRunQueued Event producer
	newTestCaseRunQueued, _ := specv03.NewTestCaseRunQueuedEvent()
	setContext(newTestCaseRunQueued, testSubjectId)
	exampleTestCaseRunQueuedEvent(newTestCaseRunQueued)
	examplesProduced[newTestCaseRunQueued.GetType().Short()] = newTestCaseRunQueued

	// TestCaseRunStarted Event producer
	newTestCaseRunStarted, _ := specv03.NewTestCaseRunStartedEvent()
	setContext(newTestCaseRunStarted, testSubjectId)
	exampleTestCaseRunStartedEvent(newTestCaseRunStarted)
	examplesProduced[newTestCaseRunStarted.GetType().Short()] = newTestCaseRunStarted

	// TestOutputPublished Event producer
	newTestOutputPublished, _ := specv03.NewTestOutputPublishedEvent()
	setContext(newTestOutputPublished, testSubjectId)
	exampleTestOutputPublishedEvent(newTestOutputPublished)
	examplesProduced[newTestOutputPublished.GetType().Short()] = newTestOutputPublished

	// TestSuiteRunFinished Event producer
	newTestSuiteRunFinished, _ := specv03.NewTestSuiteRunFinishedEvent()
	setContext(newTestSuiteRunFinished, testSubjectId)
	exampleTestSuiteRunFinishedEvent(newTestSuiteRunFinished)
	examplesProduced[newTestSuiteRunFinished.GetType().Short()] = newTestSuiteRunFinished

	// TestSuiteRunQueued Event producer
	newTestSuiteRunQueued, _ := specv03.NewTestSuiteRunQueuedEvent()
	setContext(newTestSuiteRunQueued, testSubjectId)
	exampleTestSuiteRunQueuedEvent(newTestSuiteRunQueued)
	examplesProduced[newTestSuiteRunQueued.GetType().Short()] = newTestSuiteRunQueued

	// TestSuiteRunStarted Event producer
	newTestSuiteRunStarted, _ := specv03.NewTestSuiteRunStartedEvent()
	setContext(newTestSuiteRunStarted, testSubjectId)
	exampleTestSuiteRunStartedEvent(newTestSuiteRunStarted)
	examplesProduced[newTestSuiteRunStarted.GetType().Short()] = newTestSuiteRunStarted

}
