// Code generated by tools/generator. DO NOT EDIT.

/*
Copyright 2023 The CDEvents Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

SPDX-License-Identifier: Apache-2.0
*/

package api

import (
	_ "embed"
	"fmt"
	"time"
)

//go:embed spec/schemas/incidentreported.json
var incidentreportedschema string

var (
	// IncidentReported event v0.1.0
	IncidentReportedEventV1 CDEventType = CDEventType{
		Subject:   "incident",
		Predicate: "reported",
		Version:   "0.1.0",
	}
)

type IncidentReportedSubjectContent struct {
	ArtifactId string `json:"artifactId" validate:"purl"`

	Description string `json:"description"`

	Environment Reference `json:"environment"`

	Service Reference `json:"service"`

	TicketURI string `json:"ticketURI"`
}

type IncidentReportedSubject struct {
	SubjectBase
	Content IncidentReportedSubjectContent `json:"content"`
}

func (sc IncidentReportedSubject) GetEventType() CDEventType {
	return IncidentReportedEventV1
}

func (sc IncidentReportedSubject) GetSubjectType() SubjectType {
	return "incident"
}

type IncidentReportedEvent struct {
	Context Context                 `json:"context"`
	Subject IncidentReportedSubject `json:"subject"`
	CDEventCustomData
}

// CDEventsReader implementation

func (e IncidentReportedEvent) GetType() CDEventType {
	return IncidentReportedEventV1
}

func (e IncidentReportedEvent) GetVersion() string {
	return CDEventsSpecVersion
}

func (e IncidentReportedEvent) GetId() string {
	return e.Context.Id
}

func (e IncidentReportedEvent) GetSource() string {
	return e.Context.Source
}

func (e IncidentReportedEvent) GetTimestamp() time.Time {
	return e.Context.Timestamp
}

func (e IncidentReportedEvent) GetSubjectId() string {
	return e.Subject.Id
}

func (e IncidentReportedEvent) GetSubjectSource() string {
	return e.Subject.Source
}

func (e IncidentReportedEvent) GetSubject() Subject {
	return e.Subject
}

func (e IncidentReportedEvent) GetCustomData() (interface{}, error) {
	return GetCustomData(e.CustomDataContentType, e.CustomData)
}

func (e IncidentReportedEvent) GetCustomDataAs(receiver interface{}) error {
	return GetCustomDataAs(e, receiver)
}

func (e IncidentReportedEvent) GetCustomDataRaw() ([]byte, error) {
	return GetCustomDataRaw(e.CustomDataContentType, e.CustomData)
}

func (e IncidentReportedEvent) GetCustomDataContentType() string {
	return e.CustomDataContentType
}

// CDEventsWriter implementation

func (e *IncidentReportedEvent) SetId(id string) {
	e.Context.Id = id
}

func (e *IncidentReportedEvent) SetSource(source string) {
	e.Context.Source = source
	// Default the subject source to the event source
	if e.Subject.Source == "" {
		e.Subject.Source = source
	}
}

func (e *IncidentReportedEvent) SetTimestamp(timestamp time.Time) {
	e.Context.Timestamp = timestamp
}

func (e *IncidentReportedEvent) SetSubjectId(subjectId string) {
	e.Subject.Id = subjectId
}

func (e *IncidentReportedEvent) SetSubjectSource(subjectSource string) {
	e.Subject.Source = subjectSource
}

func (e *IncidentReportedEvent) SetCustomData(contentType string, data interface{}) error {
	err := CheckCustomData(contentType, data)
	if err != nil {
		return err
	}
	e.CustomData = data
	e.CustomDataContentType = contentType
	return nil
}

func (e IncidentReportedEvent) GetSchema() (string, string) {
	eType := e.GetType()
	return fmt.Sprintf(CDEventsSchemaURLTemplate, CDEventsSpecVersion, eType.Subject, eType.Predicate), incidentreportedschema
}

// Set subject custom fields

func (e *IncidentReportedEvent) SetSubjectArtifactId(artifactId string) {
	e.Subject.Content.ArtifactId = artifactId
}

func (e *IncidentReportedEvent) SetSubjectDescription(description string) {
	e.Subject.Content.Description = description
}

func (e *IncidentReportedEvent) SetSubjectEnvironment(environment Reference) {
	e.Subject.Content.Environment = environment
}

func (e *IncidentReportedEvent) SetSubjectService(service Reference) {
	e.Subject.Content.Service = service
}

func (e *IncidentReportedEvent) SetSubjectTicketURI(ticketURI string) {
	e.Subject.Content.TicketURI = ticketURI
}

// New creates a new IncidentReportedEvent
func NewIncidentReportedEvent() (*IncidentReportedEvent, error) {
	e := &IncidentReportedEvent{
		Context: Context{
			Type:    IncidentReportedEventV1.String(),
			Version: CDEventsSpecVersion,
		},
		Subject: IncidentReportedSubject{
			SubjectBase: SubjectBase{
				Type: "incident",
			},
		},
	}
	_, err := initCDEvent(e)
	if err != nil {
		return nil, err
	}
	return e, nil
}
