// Code generated by tools/generator. DO NOT EDIT.

/*
Copyright 2023 The CDEvents Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

SPDX-License-Identifier: Apache-2.0
*/

package api

import (
	"fmt"
	"time"

	jsonschema "github.com/santhosh-tekuri/jsonschema/v6"
)

var (
	// TicketCreated event type v0.1.0
	TicketCreatedEventTypeV0_1_0 CDEventType = CDEventType{
		Subject:   "ticket",
		Predicate: "created",
		Version:   "0.1.0",
	}
)

type TicketCreatedSubjectContentV0_1_0 struct {
	Assignees []string `json:"assignees,omitempty"`

	Creator string `json:"creator"`

	Group string `json:"group,omitempty"`

	Labels []string `json:"labels,omitempty"`

	Milestone string `json:"milestone,omitempty"`

	Priority string `json:"priority,omitempty"`

	Summary string `json:"summary"`

	TicketType string `json:"ticketType,omitempty"`

	Uri string `json:"uri"`
}

type TicketCreatedSubjectV0_1_0 struct {
	SubjectBase
	Content TicketCreatedSubjectContentV0_1_0 `json:"content"`
}

func (sc TicketCreatedSubjectV0_1_0) GetSubjectType() SubjectType {
	return "ticket"
}

type TicketCreatedEventV0_1_0 struct {
	Context ContextV04                 `json:"context"`
	Subject TicketCreatedSubjectV0_1_0 `json:"subject"`
	CDEventCustomData
}

// CDEventsReader implementation

func (e TicketCreatedEventV0_1_0) GetType() CDEventType {
	return TicketCreatedEventTypeV0_1_0
}

func (e TicketCreatedEventV0_1_0) GetVersion() string {
	return e.Context.GetVersion()
}

func (e TicketCreatedEventV0_1_0) GetId() string {
	return e.Context.Id
}

func (e TicketCreatedEventV0_1_0) GetSource() string {
	return e.Context.Source
}

func (e TicketCreatedEventV0_1_0) GetTimestamp() time.Time {
	return e.Context.Timestamp
}

func (e TicketCreatedEventV0_1_0) GetSubjectId() string {
	return e.Subject.Id
}

func (e TicketCreatedEventV0_1_0) GetSubjectSource() string {
	return e.Subject.Source
}

func (e TicketCreatedEventV0_1_0) GetSubject() Subject {
	return e.Subject
}

func (e TicketCreatedEventV0_1_0) GetCustomData() (interface{}, error) {
	return GetCustomData(e.CustomDataContentType, e.CustomData)
}

func (e TicketCreatedEventV0_1_0) GetCustomDataAs(receiver interface{}) error {
	return GetCustomDataAs(e, receiver)
}

func (e TicketCreatedEventV0_1_0) GetCustomDataRaw() ([]byte, error) {
	return GetCustomDataRaw(e.CustomDataContentType, e.CustomData)
}

func (e TicketCreatedEventV0_1_0) GetCustomDataContentType() string {
	return e.CustomDataContentType
}

// CDEventsReaderV04 implementation

func (e TicketCreatedEventV0_1_0) GetChainId() string {
	return e.Context.ChainId
}

func (e TicketCreatedEventV0_1_0) GetLinks() EmbeddedLinksArray {
	return e.Context.Links
}

func (e TicketCreatedEventV0_1_0) GetSchemaUri() string {
	return e.Context.SchemaUri
}

// GetCustomSchema looks up the SchemaUri, if any is defined. If none is defined, it returns nil.
// If it's defined and cannot be found, it returns an error.
func (e TicketCreatedEventV0_1_0) GetCustomSchema() (*jsonschema.Schema, error) {
	schemaUri := e.GetSchemaUri()
	if schemaUri == "" {
		return nil, nil
	}
	schema, found := CompiledCustomSchemas[schemaUri]
	if !found {
		return nil, fmt.Errorf("schema with id %s could not be found in the local registry", schemaUri)
	}
	return schema, nil
}

// CDEventsWriter implementation

func (e *TicketCreatedEventV0_1_0) SetId(id string) {
	e.Context.Id = id
}

func (e *TicketCreatedEventV0_1_0) SetSource(source string) {
	e.Context.Source = source
	// Default the subject source to the event source
	if e.Subject.Source == "" {
		e.Subject.Source = source
	}
}

func (e *TicketCreatedEventV0_1_0) SetTimestamp(timestamp time.Time) {
	e.Context.Timestamp = timestamp
}

func (e *TicketCreatedEventV0_1_0) SetSubjectId(subjectId string) {
	e.Subject.Id = subjectId
}

func (e *TicketCreatedEventV0_1_0) SetSubjectSource(subjectSource string) {
	e.Subject.Source = subjectSource
}

func (e *TicketCreatedEventV0_1_0) SetCustomData(contentType string, data interface{}) error {
	err := CheckCustomData(contentType, data)
	if err != nil {
		return err
	}
	e.CustomData = data
	e.CustomDataContentType = contentType
	return nil
}

func (e TicketCreatedEventV0_1_0) GetSchema() (string, *jsonschema.Schema, error) {
	eType := e.GetType()
	return CompiledSchemas.GetBySpecSubjectPredicate("0.4.1", eType.Subject, eType.Predicate, eType.Custom)
}

// CDEventsWriterV04 implementation

func (e *TicketCreatedEventV0_1_0) SetChainId(chainId string) {
	e.Context.ChainId = chainId
}

func (e *TicketCreatedEventV0_1_0) SetLinks(links EmbeddedLinksArray) {
	e.Context.Links = links
}

func (e *TicketCreatedEventV0_1_0) SetSchemaUri(schema string) {
	e.Context.SchemaUri = schema
}

func (e TicketCreatedEventV0_1_0) GetSubjectContent() interface{} {
	return e.Subject.Content
}

// Set subject custom fields

func (e *TicketCreatedEventV0_1_0) SetSubjectAssignees(assignees []string) {
	e.Subject.Content.Assignees = assignees
}

func (e *TicketCreatedEventV0_1_0) SetSubjectCreator(creator string) {
	e.Subject.Content.Creator = creator
}

func (e *TicketCreatedEventV0_1_0) SetSubjectGroup(group string) {
	e.Subject.Content.Group = group
}

func (e *TicketCreatedEventV0_1_0) SetSubjectLabels(labels []string) {
	e.Subject.Content.Labels = labels
}

func (e *TicketCreatedEventV0_1_0) SetSubjectMilestone(milestone string) {
	e.Subject.Content.Milestone = milestone
}

func (e *TicketCreatedEventV0_1_0) SetSubjectPriority(priority string) {
	e.Subject.Content.Priority = priority
}

func (e *TicketCreatedEventV0_1_0) SetSubjectSummary(summary string) {
	e.Subject.Content.Summary = summary
}

func (e *TicketCreatedEventV0_1_0) SetSubjectTicketType(ticketType string) {
	e.Subject.Content.TicketType = ticketType
}

func (e *TicketCreatedEventV0_1_0) SetSubjectUri(uri string) {
	e.Subject.Content.Uri = uri
}

// New creates a new TicketCreatedEventV0_1_0
func NewTicketCreatedEventV0_1_0(specVersion string) (*TicketCreatedEventV0_1_0, error) {
	e := &TicketCreatedEventV0_1_0{
		Context: ContextV04{
			Context: Context{
				SharedContext: SharedContext{
					Type: TicketCreatedEventTypeV0_1_0,
				},
				Version: specVersion,
			},
			ContextLinks:  ContextLinks{},
			ContextCustom: ContextCustom{},
		},
		Subject: TicketCreatedSubjectV0_1_0{
			SubjectBase: SubjectBase{
				Type: "ticket",
			},
		},
	}
	_, err := initCDEvent(e)
	if err != nil {
		return nil, err
	}
	return e, nil
}
