// Code generated by tools/generator. DO NOT EDIT.

/*
Copyright 2023 The CDEvents Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

SPDX-License-Identifier: Apache-2.0
*/

package api

import (
	"time"

	jsonschema "github.com/santhosh-tekuri/jsonschema/v6"
)

var (
	// TicketUpdated event type v0.1.0
	TicketUpdatedEventTypeV0_1_0 CDEventType = CDEventType{
		Subject:   "ticket",
		Predicate: "updated",
		Version:   "0.1.0",
	}
)

type TicketUpdatedSubjectContentV0_1_0 struct {
	Assignees []string `json:"assignees,omitempty"`

	Creator string `json:"creator,omitempty"`

	Group string `json:"group,omitempty"`

	Labels []string `json:"labels,omitempty"`

	Milestone string `json:"milestone,omitempty"`

	Priority string `json:"priority,omitempty"`

	Summary string `json:"summary,omitempty"`

	TicketType string `json:"ticketType,omitempty"`

	UpdatedBy string `json:"updatedBy,omitempty"`

	Uri string `json:"uri"`
}

type TicketUpdatedSubjectV0_1_0 struct {
	SubjectBase
	Content TicketUpdatedSubjectContentV0_1_0 `json:"content"`
}

func (sc TicketUpdatedSubjectV0_1_0) GetSubjectType() SubjectType {
	return "ticket"
}

type TicketUpdatedEventV0_1_0 struct {
	Context ContextV04                 `json:"context"`
	Subject TicketUpdatedSubjectV0_1_0 `json:"subject"`
	CDEventCustomData
}

// CDEventsReader implementation

func (e TicketUpdatedEventV0_1_0) GetType() CDEventType {
	return TicketUpdatedEventTypeV0_1_0
}

func (e TicketUpdatedEventV0_1_0) GetVersion() string {
	return e.Context.GetVersion()
}

func (e TicketUpdatedEventV0_1_0) GetId() string {
	return e.Context.Id
}

func (e TicketUpdatedEventV0_1_0) GetSource() string {
	return e.Context.Source
}

func (e TicketUpdatedEventV0_1_0) GetTimestamp() time.Time {
	return e.Context.Timestamp
}

func (e TicketUpdatedEventV0_1_0) GetSubjectId() string {
	return e.Subject.Id
}

func (e TicketUpdatedEventV0_1_0) GetSubjectSource() string {
	return e.Subject.Source
}

func (e TicketUpdatedEventV0_1_0) GetSubject() Subject {
	return e.Subject
}

func (e TicketUpdatedEventV0_1_0) GetCustomData() (interface{}, error) {
	return GetCustomData(e.CustomDataContentType, e.CustomData)
}

func (e TicketUpdatedEventV0_1_0) GetCustomDataAs(receiver interface{}) error {
	return GetCustomDataAs(e, receiver)
}

func (e TicketUpdatedEventV0_1_0) GetCustomDataRaw() ([]byte, error) {
	return GetCustomDataRaw(e.CustomDataContentType, e.CustomData)
}

func (e TicketUpdatedEventV0_1_0) GetCustomDataContentType() string {
	return e.CustomDataContentType
}

// CDEventsReaderV04 implementation

func (e TicketUpdatedEventV0_1_0) GetChainId() string {
	return e.Context.ChainId
}

func (e TicketUpdatedEventV0_1_0) GetLinks() EmbeddedLinksArray {
	return e.Context.Links
}

func (e TicketUpdatedEventV0_1_0) GetSchemaUri() string {
	return e.Context.SchemaUri
}

// CDEventsWriter implementation

func (e *TicketUpdatedEventV0_1_0) SetId(id string) {
	e.Context.Id = id
}

func (e *TicketUpdatedEventV0_1_0) SetSource(source string) {
	e.Context.Source = source
	// Default the subject source to the event source
	if e.Subject.Source == "" {
		e.Subject.Source = source
	}
}

func (e *TicketUpdatedEventV0_1_0) SetTimestamp(timestamp time.Time) {
	e.Context.Timestamp = timestamp
}

func (e *TicketUpdatedEventV0_1_0) SetSubjectId(subjectId string) {
	e.Subject.Id = subjectId
}

func (e *TicketUpdatedEventV0_1_0) SetSubjectSource(subjectSource string) {
	e.Subject.Source = subjectSource
}

func (e *TicketUpdatedEventV0_1_0) SetCustomData(contentType string, data interface{}) error {
	err := CheckCustomData(contentType, data)
	if err != nil {
		return err
	}
	e.CustomData = data
	e.CustomDataContentType = contentType
	return nil
}

func (e TicketUpdatedEventV0_1_0) GetSchema() (string, *jsonschema.Schema, error) {
	eType := e.GetType()
	return CompiledSchemas.GetBySpecSubjectPredicate("0.4.1", eType.Subject, eType.Predicate, eType.Custom)
}

// CDEventsWriterV04 implementation

func (e *TicketUpdatedEventV0_1_0) SetChainId(chainId string) {
	e.Context.ChainId = chainId
}

func (e *TicketUpdatedEventV0_1_0) SetLinks(links EmbeddedLinksArray) {
	e.Context.Links = links
}

func (e *TicketUpdatedEventV0_1_0) SetSchemaUri(schema string) {
	e.Context.SchemaUri = schema
}

func (e TicketUpdatedEventV0_1_0) GetSubjectContent() interface{} {
	return e.Subject.Content
}

// Set subject custom fields

func (e *TicketUpdatedEventV0_1_0) SetSubjectAssignees(assignees []string) {
	e.Subject.Content.Assignees = assignees
}

func (e *TicketUpdatedEventV0_1_0) SetSubjectCreator(creator string) {
	e.Subject.Content.Creator = creator
}

func (e *TicketUpdatedEventV0_1_0) SetSubjectGroup(group string) {
	e.Subject.Content.Group = group
}

func (e *TicketUpdatedEventV0_1_0) SetSubjectLabels(labels []string) {
	e.Subject.Content.Labels = labels
}

func (e *TicketUpdatedEventV0_1_0) SetSubjectMilestone(milestone string) {
	e.Subject.Content.Milestone = milestone
}

func (e *TicketUpdatedEventV0_1_0) SetSubjectPriority(priority string) {
	e.Subject.Content.Priority = priority
}

func (e *TicketUpdatedEventV0_1_0) SetSubjectSummary(summary string) {
	e.Subject.Content.Summary = summary
}

func (e *TicketUpdatedEventV0_1_0) SetSubjectTicketType(ticketType string) {
	e.Subject.Content.TicketType = ticketType
}

func (e *TicketUpdatedEventV0_1_0) SetSubjectUpdatedBy(updatedBy string) {
	e.Subject.Content.UpdatedBy = updatedBy
}

func (e *TicketUpdatedEventV0_1_0) SetSubjectUri(uri string) {
	e.Subject.Content.Uri = uri
}

// New creates a new TicketUpdatedEventV0_1_0
func NewTicketUpdatedEventV0_1_0(specVersion string) (*TicketUpdatedEventV0_1_0, error) {
	e := &TicketUpdatedEventV0_1_0{
		Context: ContextV04{
			Context{
				Type:    TicketUpdatedEventTypeV0_1_0,
				Version: specVersion,
			},
			ContextLinks{},
			ContextCustom{},
		},
		Subject: TicketUpdatedSubjectV0_1_0{
			SubjectBase: SubjectBase{
				Type: "ticket",
			},
		},
	}
	_, err := initCDEvent(e)
	if err != nil {
		return nil, err
	}
	return e, nil
}
