// Code generated by tools/generator. DO NOT EDIT.

/*
Copyright 2023 The CDEvents Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

SPDX-License-Identifier: Apache-2.0
*/

package api

import (
	"fmt"
	"time"

	jsonschema "github.com/santhosh-tekuri/jsonschema/v6"
)

var (
	// TicketClosed event type v0.1.0
	TicketClosedEventTypeV0_1_0 CDEventType = CDEventType{
		Subject:   "ticket",
		Predicate: "closed",
		Version:   "0.1.0",
	}
)

type TicketClosedSubjectContentV0_1_0 struct {
	Assignees []string `json:"assignees,omitempty"`

	Creator string `json:"creator,omitempty"`

	Group string `json:"group,omitempty"`

	Labels []string `json:"labels,omitempty"`

	Milestone string `json:"milestone,omitempty"`

	Priority string `json:"priority,omitempty"`

	Resolution string `json:"resolution"`

	Summary string `json:"summary,omitempty"`

	TicketType string `json:"ticketType,omitempty"`

	UpdatedBy string `json:"updatedBy,omitempty"`

	Uri string `json:"uri"`
}

type TicketClosedSubjectV0_1_0 struct {
	SubjectBase
	Content TicketClosedSubjectContentV0_1_0 `json:"content"`
}

func (sc TicketClosedSubjectV0_1_0) GetSubjectType() SubjectType {
	return "ticket"
}

type TicketClosedEventV0_1_0 struct {
	Context ContextV04                `json:"context"`
	Subject TicketClosedSubjectV0_1_0 `json:"subject"`
	CDEventCustomData
}

// CDEventsReader implementation

func (e TicketClosedEventV0_1_0) GetType() CDEventType {
	return TicketClosedEventTypeV0_1_0
}

func (e TicketClosedEventV0_1_0) GetVersion() string {
	return e.Context.GetVersion()
}

func (e TicketClosedEventV0_1_0) GetId() string {
	return e.Context.ID
}

func (e TicketClosedEventV0_1_0) GetSource() string {
	return e.Context.Source
}

func (e TicketClosedEventV0_1_0) GetTimestamp() time.Time {
	return e.Context.Timestamp
}

func (e TicketClosedEventV0_1_0) GetSubjectId() string {
	return e.Subject.ID
}

func (e TicketClosedEventV0_1_0) GetSubjectSource() string {
	return e.Subject.Source
}

func (e TicketClosedEventV0_1_0) GetSubject() Subject {
	return e.Subject
}

func (e TicketClosedEventV0_1_0) GetCustomData() (interface{}, error) {
	return GetCustomData(e.CustomDataContentType, e.CustomData)
}

func (e TicketClosedEventV0_1_0) GetCustomDataAs(receiver interface{}) error {
	return GetCustomDataAs(e, receiver)
}

func (e TicketClosedEventV0_1_0) GetCustomDataRaw() ([]byte, error) {
	return GetCustomDataRaw(e.CustomDataContentType, e.CustomData)
}

func (e TicketClosedEventV0_1_0) GetCustomDataContentType() string {
	return e.CustomDataContentType
}

// CDEventsReaderV04 implementation

func (e TicketClosedEventV0_1_0) GetChainId() string {
	return e.Context.ChainID
}

func (e TicketClosedEventV0_1_0) GetLinks() EmbeddedLinksArray {
	return e.Context.Links
}

func (e TicketClosedEventV0_1_0) GetSchemaUri() string {
	return e.Context.SchemaURI
}

// GetCustomSchema looks up the schemaURI, if any is defined. If none is defined, it returns nil.
// If it's defined and cannot be found, it returns an error.
func (e TicketClosedEventV0_1_0) GetCustomSchema() (*jsonschema.Schema, error) {
	schemaURI := e.GetSchemaUri()
	if schemaURI == "" {
		return nil, nil
	}
	schema, found := CompiledCustomSchemas[schemaURI]
	if !found {
		return nil, fmt.Errorf("schema with id %s could not be found in the local registry", schemaURI)
	}
	return schema, nil
}

// CDEventsWriter implementation

func (e *TicketClosedEventV0_1_0) SetId(id string) {
	e.Context.ID = id
}

func (e *TicketClosedEventV0_1_0) SetSource(source string) {
	e.Context.Source = source
	// Default the subject source to the event source
	if e.Subject.Source == "" {
		e.Subject.Source = source
	}
}

func (e *TicketClosedEventV0_1_0) SetTimestamp(timestamp time.Time) {
	e.Context.Timestamp = timestamp
}

func (e *TicketClosedEventV0_1_0) SetSubjectId(subjectId string) {
	e.Subject.ID = subjectId
}

func (e *TicketClosedEventV0_1_0) SetSubjectSource(subjectSource string) {
	e.Subject.Source = subjectSource
}

func (e *TicketClosedEventV0_1_0) SetCustomData(contentType string, data interface{}) error {
	err := CheckCustomData(contentType, data)
	if err != nil {
		return err
	}
	e.CustomData = data
	e.CustomDataContentType = contentType
	return nil
}

func (e TicketClosedEventV0_1_0) GetSchema() (string, *jsonschema.Schema, error) {
	eType := e.GetType()
	return CompiledSchemas.GetBySpecSubjectPredicate("0.4.1", eType.Subject, eType.Predicate, eType.Custom)
}

// CDEventsWriterV04 implementation

func (e *TicketClosedEventV0_1_0) SetChainId(chainId string) {
	e.Context.ChainID = chainId
}

func (e *TicketClosedEventV0_1_0) SetLinks(links EmbeddedLinksArray) {
	e.Context.Links = links
}

func (e *TicketClosedEventV0_1_0) SetSchemaUri(schema string) {
	e.Context.SchemaURI = schema
}

func (e TicketClosedEventV0_1_0) GetSubjectContent() interface{} {
	return e.Subject.Content
}

// Set subject custom fields

func (e *TicketClosedEventV0_1_0) SetSubjectAssignees(assignees []string) {
	e.Subject.Content.Assignees = assignees
}

func (e *TicketClosedEventV0_1_0) SetSubjectCreator(creator string) {
	e.Subject.Content.Creator = creator
}

func (e *TicketClosedEventV0_1_0) SetSubjectGroup(group string) {
	e.Subject.Content.Group = group
}

func (e *TicketClosedEventV0_1_0) SetSubjectLabels(labels []string) {
	e.Subject.Content.Labels = labels
}

func (e *TicketClosedEventV0_1_0) SetSubjectMilestone(milestone string) {
	e.Subject.Content.Milestone = milestone
}

func (e *TicketClosedEventV0_1_0) SetSubjectPriority(priority string) {
	e.Subject.Content.Priority = priority
}

func (e *TicketClosedEventV0_1_0) SetSubjectResolution(resolution string) {
	e.Subject.Content.Resolution = resolution
}

func (e *TicketClosedEventV0_1_0) SetSubjectSummary(summary string) {
	e.Subject.Content.Summary = summary
}

func (e *TicketClosedEventV0_1_0) SetSubjectTicketType(ticketType string) {
	e.Subject.Content.TicketType = ticketType
}

func (e *TicketClosedEventV0_1_0) SetSubjectUpdatedBy(updatedBy string) {
	e.Subject.Content.UpdatedBy = updatedBy
}

func (e *TicketClosedEventV0_1_0) SetSubjectUri(uri string) {
	e.Subject.Content.Uri = uri
}

// New creates a new TicketClosedEventV0_1_0
func NewTicketClosedEventV0_1_0(specVersion string) (*TicketClosedEventV0_1_0, error) {
	e := &TicketClosedEventV0_1_0{
		Context: ContextV04{
			Context{
				Type:    TicketClosedEventTypeV0_1_0,
				Version: specVersion,
			},
			ContextLinks{},
			ContextCustom{},
		},
		Subject: TicketClosedSubjectV0_1_0{
			SubjectBase: SubjectBase{
				Type: "ticket",
			},
		},
	}
	_, err := initCDEvent(e)
	if err != nil {
		return nil, err
	}
	return e, nil
}
