// Code generated by tools/generator. DO NOT EDIT.

/*
Copyright 2023 The CDEvents Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

SPDX-License-Identifier: Apache-2.0
*/

package v03

import (
	"fmt"

	"github.com/cdevents/sdk-go/pkg/api"
)

var CDEventsTypes = []api.CDEvent{
	&ArtifactPackagedEvent{},
	&ArtifactPublishedEvent{},
	&ArtifactSignedEvent{},
	&BranchCreatedEvent{},
	&BranchDeletedEvent{},
	&BuildFinishedEvent{},
	&BuildQueuedEvent{},
	&BuildStartedEvent{},
	&ChangeAbandonedEvent{},
	&ChangeCreatedEvent{},
	&ChangeMergedEvent{},
	&ChangeReviewedEvent{},
	&ChangeUpdatedEvent{},
	&EnvironmentCreatedEvent{},
	&EnvironmentDeletedEvent{},
	&EnvironmentModifiedEvent{},
	&IncidentDetectedEvent{},
	&IncidentReportedEvent{},
	&IncidentResolvedEvent{},
	&PipelineRunFinishedEvent{},
	&PipelineRunQueuedEvent{},
	&PipelineRunStartedEvent{},
	&RepositoryCreatedEvent{},
	&RepositoryDeletedEvent{},
	&RepositoryModifiedEvent{},
	&ServiceDeployedEvent{},
	&ServicePublishedEvent{},
	&ServiceRemovedEvent{},
	&ServiceRolledbackEvent{},
	&ServiceUpgradedEvent{},
	&TaskRunFinishedEvent{},
	&TaskRunStartedEvent{},
	&TestCaseRunFinishedEvent{},
	&TestCaseRunQueuedEvent{},
	&TestCaseRunStartedEvent{},
	&TestOutputPublishedEvent{},
	&TestSuiteRunFinishedEvent{},
	&TestSuiteRunQueuedEvent{},
	&TestSuiteRunStartedEvent{},
}

var CDEventsByUnversionedTypes map[string]api.CDEvent

func init() {
	// Set up CDEventsByUnversionedTypes for convenience
	CDEventsByUnversionedTypes = make(map[string]api.CDEvent)
	for _, event := range CDEventsTypes {
		CDEventsByUnversionedTypes[event.GetType().UnversionedString()] = event
	}
}

// NewCDEvent produces a CDEvent by type
// This function can be used by users but it's meant mainly for testing purposes
func NewCDEvent(eventType, specVersion string) (api.CDEvent, error) {
	switch eventType {
	case api.ArtifactPackagedEventTypeV0_1_1.String():
		return NewArtifactPackagedEvent()
	case api.ArtifactPublishedEventTypeV0_1_1.String():
		return NewArtifactPublishedEvent()
	case api.ArtifactSignedEventTypeV0_1_0.String():
		return NewArtifactSignedEvent()
	case api.BranchCreatedEventTypeV0_1_2.String():
		return NewBranchCreatedEvent()
	case api.BranchDeletedEventTypeV0_1_2.String():
		return NewBranchDeletedEvent()
	case api.BuildFinishedEventTypeV0_1_1.String():
		return NewBuildFinishedEvent()
	case api.BuildQueuedEventTypeV0_1_1.String():
		return NewBuildQueuedEvent()
	case api.BuildStartedEventTypeV0_1_1.String():
		return NewBuildStartedEvent()
	case api.ChangeAbandonedEventTypeV0_1_2.String():
		return NewChangeAbandonedEvent()
	case api.ChangeCreatedEventTypeV0_1_2.String():
		return NewChangeCreatedEvent()
	case api.ChangeMergedEventTypeV0_1_2.String():
		return NewChangeMergedEvent()
	case api.ChangeReviewedEventTypeV0_1_2.String():
		return NewChangeReviewedEvent()
	case api.ChangeUpdatedEventTypeV0_1_2.String():
		return NewChangeUpdatedEvent()
	case api.EnvironmentCreatedEventTypeV0_1_1.String():
		return NewEnvironmentCreatedEvent()
	case api.EnvironmentDeletedEventTypeV0_1_1.String():
		return NewEnvironmentDeletedEvent()
	case api.EnvironmentModifiedEventTypeV0_1_1.String():
		return NewEnvironmentModifiedEvent()
	case api.IncidentDetectedEventTypeV0_1_0.String():
		return NewIncidentDetectedEvent()
	case api.IncidentReportedEventTypeV0_1_0.String():
		return NewIncidentReportedEvent()
	case api.IncidentResolvedEventTypeV0_1_0.String():
		return NewIncidentResolvedEvent()
	case api.PipelineRunFinishedEventTypeV0_1_1.String():
		return NewPipelineRunFinishedEvent()
	case api.PipelineRunQueuedEventTypeV0_1_1.String():
		return NewPipelineRunQueuedEvent()
	case api.PipelineRunStartedEventTypeV0_1_1.String():
		return NewPipelineRunStartedEvent()
	case api.RepositoryCreatedEventTypeV0_1_1.String():
		return NewRepositoryCreatedEvent()
	case api.RepositoryDeletedEventTypeV0_1_1.String():
		return NewRepositoryDeletedEvent()
	case api.RepositoryModifiedEventTypeV0_1_1.String():
		return NewRepositoryModifiedEvent()
	case api.ServiceDeployedEventTypeV0_1_1.String():
		return NewServiceDeployedEvent()
	case api.ServicePublishedEventTypeV0_1_1.String():
		return NewServicePublishedEvent()
	case api.ServiceRemovedEventTypeV0_1_1.String():
		return NewServiceRemovedEvent()
	case api.ServiceRolledbackEventTypeV0_1_1.String():
		return NewServiceRolledbackEvent()
	case api.ServiceUpgradedEventTypeV0_1_1.String():
		return NewServiceUpgradedEvent()
	case api.TaskRunFinishedEventTypeV0_1_1.String():
		return NewTaskRunFinishedEvent()
	case api.TaskRunStartedEventTypeV0_1_1.String():
		return NewTaskRunStartedEvent()
	case api.TestCaseRunFinishedEventTypeV0_1_0.String():
		return NewTestCaseRunFinishedEvent()
	case api.TestCaseRunQueuedEventTypeV0_1_0.String():
		return NewTestCaseRunQueuedEvent()
	case api.TestCaseRunStartedEventTypeV0_1_0.String():
		return NewTestCaseRunStartedEvent()
	case api.TestOutputPublishedEventTypeV0_1_0.String():
		return NewTestOutputPublishedEvent()
	case api.TestSuiteRunFinishedEventTypeV0_1_0.String():
		return NewTestSuiteRunFinishedEvent()
	case api.TestSuiteRunQueuedEventTypeV0_1_0.String():
		return NewTestSuiteRunQueuedEvent()
	case api.TestSuiteRunStartedEventTypeV0_1_0.String():
		return NewTestSuiteRunStartedEvent()
	default:
		return nil, fmt.Errorf("event %v not supported", eventType)
	}
}
