// Code generated by tools/generator. DO NOT EDIT.

/*
Copyright 2023 The CDEvents Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

SPDX-License-Identifier: Apache-2.0
*/

package v05_test

import (
	"github.com/cdevents/sdk-go/pkg/api"
	apiv05 "github.com/cdevents/sdk-go/pkg/api/v05"
)

func init() {
	tests = []testNewCDEventType{}
	tests = append(tests, testNewCDEventType{
		name:      "artifact deleted",
		eventType: apiv05.ArtifactDeletedEventType.String(),
		expectedEvent: &apiv05.ArtifactDeletedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.ArtifactDeletedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.ArtifactDeletedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "artifact downloaded",
		eventType: apiv05.ArtifactDownloadedEventType.String(),
		expectedEvent: &apiv05.ArtifactDownloadedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.ArtifactDownloadedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.ArtifactDownloadedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "artifact packaged",
		eventType: apiv05.ArtifactPackagedEventType.String(),
		expectedEvent: &apiv05.ArtifactPackagedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.ArtifactPackagedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.ArtifactPackagedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "artifact published",
		eventType: apiv05.ArtifactPublishedEventType.String(),
		expectedEvent: &apiv05.ArtifactPublishedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.ArtifactPublishedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.ArtifactPublishedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "artifact signed",
		eventType: apiv05.ArtifactSignedEventType.String(),
		expectedEvent: &apiv05.ArtifactSignedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.ArtifactSignedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.ArtifactSignedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "branch created",
		eventType: apiv05.BranchCreatedEventType.String(),
		expectedEvent: &apiv05.BranchCreatedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.BranchCreatedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.BranchCreatedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "branch deleted",
		eventType: apiv05.BranchDeletedEventType.String(),
		expectedEvent: &apiv05.BranchDeletedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.BranchDeletedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.BranchDeletedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "build finished",
		eventType: apiv05.BuildFinishedEventType.String(),
		expectedEvent: &apiv05.BuildFinishedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.BuildFinishedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.BuildFinishedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "build queued",
		eventType: apiv05.BuildQueuedEventType.String(),
		expectedEvent: &apiv05.BuildQueuedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.BuildQueuedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.BuildQueuedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "build started",
		eventType: apiv05.BuildStartedEventType.String(),
		expectedEvent: &apiv05.BuildStartedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.BuildStartedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.BuildStartedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "change abandoned",
		eventType: apiv05.ChangeAbandonedEventType.String(),
		expectedEvent: &apiv05.ChangeAbandonedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.ChangeAbandonedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.ChangeAbandonedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "change created",
		eventType: apiv05.ChangeCreatedEventType.String(),
		expectedEvent: &apiv05.ChangeCreatedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.ChangeCreatedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.ChangeCreatedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "change merged",
		eventType: apiv05.ChangeMergedEventType.String(),
		expectedEvent: &apiv05.ChangeMergedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.ChangeMergedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.ChangeMergedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "change reviewed",
		eventType: apiv05.ChangeReviewedEventType.String(),
		expectedEvent: &apiv05.ChangeReviewedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.ChangeReviewedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.ChangeReviewedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "change updated",
		eventType: apiv05.ChangeUpdatedEventType.String(),
		expectedEvent: &apiv05.ChangeUpdatedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.ChangeUpdatedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.ChangeUpdatedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "environment created",
		eventType: apiv05.EnvironmentCreatedEventType.String(),
		expectedEvent: &apiv05.EnvironmentCreatedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.EnvironmentCreatedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.EnvironmentCreatedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "environment deleted",
		eventType: apiv05.EnvironmentDeletedEventType.String(),
		expectedEvent: &apiv05.EnvironmentDeletedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.EnvironmentDeletedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.EnvironmentDeletedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "environment modified",
		eventType: apiv05.EnvironmentModifiedEventType.String(),
		expectedEvent: &apiv05.EnvironmentModifiedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.EnvironmentModifiedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.EnvironmentModifiedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "incident detected",
		eventType: apiv05.IncidentDetectedEventType.String(),
		expectedEvent: &apiv05.IncidentDetectedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.IncidentDetectedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.IncidentDetectedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "incident reported",
		eventType: apiv05.IncidentReportedEventType.String(),
		expectedEvent: &apiv05.IncidentReportedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.IncidentReportedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.IncidentReportedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "incident resolved",
		eventType: apiv05.IncidentResolvedEventType.String(),
		expectedEvent: &apiv05.IncidentResolvedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.IncidentResolvedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.IncidentResolvedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "pipelinerun finished",
		eventType: apiv05.PipelineRunFinishedEventType.String(),
		expectedEvent: &apiv05.PipelineRunFinishedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.PipelineRunFinishedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.PipelineRunFinishedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "pipelinerun queued",
		eventType: apiv05.PipelineRunQueuedEventType.String(),
		expectedEvent: &apiv05.PipelineRunQueuedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.PipelineRunQueuedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.PipelineRunQueuedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "pipelinerun started",
		eventType: apiv05.PipelineRunStartedEventType.String(),
		expectedEvent: &apiv05.PipelineRunStartedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.PipelineRunStartedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.PipelineRunStartedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "repository created",
		eventType: apiv05.RepositoryCreatedEventType.String(),
		expectedEvent: &apiv05.RepositoryCreatedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.RepositoryCreatedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.RepositoryCreatedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "repository deleted",
		eventType: apiv05.RepositoryDeletedEventType.String(),
		expectedEvent: &apiv05.RepositoryDeletedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.RepositoryDeletedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.RepositoryDeletedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "repository modified",
		eventType: apiv05.RepositoryModifiedEventType.String(),
		expectedEvent: &apiv05.RepositoryModifiedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.RepositoryModifiedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.RepositoryModifiedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "service deployed",
		eventType: apiv05.ServiceDeployedEventType.String(),
		expectedEvent: &apiv05.ServiceDeployedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.ServiceDeployedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.ServiceDeployedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "service published",
		eventType: apiv05.ServicePublishedEventType.String(),
		expectedEvent: &apiv05.ServicePublishedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.ServicePublishedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.ServicePublishedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "service removed",
		eventType: apiv05.ServiceRemovedEventType.String(),
		expectedEvent: &apiv05.ServiceRemovedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.ServiceRemovedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.ServiceRemovedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "service rolledback",
		eventType: apiv05.ServiceRolledbackEventType.String(),
		expectedEvent: &apiv05.ServiceRolledbackEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.ServiceRolledbackEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.ServiceRolledbackSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "service upgraded",
		eventType: apiv05.ServiceUpgradedEventType.String(),
		expectedEvent: &apiv05.ServiceUpgradedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.ServiceUpgradedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.ServiceUpgradedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "taskrun finished",
		eventType: apiv05.TaskRunFinishedEventType.String(),
		expectedEvent: &apiv05.TaskRunFinishedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.TaskRunFinishedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.TaskRunFinishedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "taskrun started",
		eventType: apiv05.TaskRunStartedEventType.String(),
		expectedEvent: &apiv05.TaskRunStartedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.TaskRunStartedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.TaskRunStartedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "testcaserun finished",
		eventType: apiv05.TestCaseRunFinishedEventType.String(),
		expectedEvent: &apiv05.TestCaseRunFinishedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.TestCaseRunFinishedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.TestCaseRunFinishedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "testcaserun queued",
		eventType: apiv05.TestCaseRunQueuedEventType.String(),
		expectedEvent: &apiv05.TestCaseRunQueuedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.TestCaseRunQueuedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.TestCaseRunQueuedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "testcaserun skipped",
		eventType: apiv05.TestCaseRunSkippedEventType.String(),
		expectedEvent: &apiv05.TestCaseRunSkippedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.TestCaseRunSkippedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.TestCaseRunSkippedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "testcaserun started",
		eventType: apiv05.TestCaseRunStartedEventType.String(),
		expectedEvent: &apiv05.TestCaseRunStartedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.TestCaseRunStartedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.TestCaseRunStartedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "testoutput published",
		eventType: apiv05.TestOutputPublishedEventType.String(),
		expectedEvent: &apiv05.TestOutputPublishedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.TestOutputPublishedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.TestOutputPublishedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "testsuiterun finished",
		eventType: apiv05.TestSuiteRunFinishedEventType.String(),
		expectedEvent: &apiv05.TestSuiteRunFinishedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.TestSuiteRunFinishedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.TestSuiteRunFinishedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "testsuiterun queued",
		eventType: apiv05.TestSuiteRunQueuedEventType.String(),
		expectedEvent: &apiv05.TestSuiteRunQueuedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.TestSuiteRunQueuedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.TestSuiteRunQueuedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "testsuiterun started",
		eventType: apiv05.TestSuiteRunStartedEventType.String(),
		expectedEvent: &apiv05.TestSuiteRunStartedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.TestSuiteRunStartedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.TestSuiteRunStartedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "ticket closed",
		eventType: apiv05.TicketClosedEventType.String(),
		expectedEvent: &apiv05.TicketClosedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.TicketClosedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.TicketClosedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "ticket created",
		eventType: apiv05.TicketCreatedEventType.String(),
		expectedEvent: &apiv05.TicketCreatedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.TicketCreatedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.TicketCreatedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "ticket updated",
		eventType: apiv05.TicketUpdatedEventType.String(),
		expectedEvent: &apiv05.TicketUpdatedEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.TicketUpdatedEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.TicketUpdatedSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
	tests = append(tests, testNewCDEventType{
		name:      "custom type",
		eventType: apiv05.CustomTypeEventType.String(),
		expectedEvent: &apiv05.CustomTypeEvent{
			Context: api.ContextV05{
				SharedContext: api.SharedContext{
					Type:      apiv05.CustomTypeEventType,
					Timestamp: timeNow(),
					Id:        testUUID(),
				},
				SpecVersion: "0.5.0",
			},
			Subject: apiv05.CustomTypeSubject{
				SubjectBaseV05: api.SubjectBaseV05{},
			},
		},
	})
}
