name: Test and Coverage

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - README.md
      - .gitignore
  push:
    branches:
      - main
  merge_group:


permissions: {}

jobs:
  coverage:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        go-version:
          - '1.25'

    env:
      GOPATH: /home/runner/go

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: recursive
        persist-credentials: false

    - name: Setup Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true

    - name: Generate coverage report
      run: make test

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
